name: Publish to npm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Update package.json version
        run: |
          TAG=$(git tag --points-at HEAD | tail -n 1)
          sed -i "s/\"version\": \".*\"/\"version\": \"$TAG\"/g" package.json
          cat package.json
      - name: Install dependencies and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm ci
          npm publish --access public
